// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTransaction(arg1:string,arg2:number):Promise<string>;

export function GetAccount():Promise<string>;

export function GetRecurringList():Promise<string>;

export function GetTransactions():Promise<string>;
