// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTransaction(arg1:string,arg2:number):Promise<string>;

export function ApplyRecurring(arg1:number):Promise<string>;

export function DeleteTransaction(arg1:number):Promise<string>;

export function GetAccount():Promise<string>;

export function GetRecurringList():Promise<string>;

export function GetTransactions(arg1:number,arg2:number):Promise<string>;

export function UpdateTransaction(arg1:number,arg2:string,arg3:number):Promise<string>;
