// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTransaction(arg1, arg2) {
  return window['go']['main']['App']['AddTransaction'](arg1, arg2);
}

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetRecurringList() {
  return window['go']['main']['App']['GetRecurringList']();
}

export function GetTransactions() {
  return window['go']['main']['App']['GetTransactions']();
}
